---
title: "Project 1"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(stringr)
```

```{r}
data <- readLines("https://raw.githubusercontent.com/Jeovany97/Data-607/refs/heads/main/Project%201/tournamentinfo.txt", warn = FALSE)

#Removing dash lines and header row
clean_data <- data[!str_detect(data, "^-+$")]
clean_data <- clean_data[-(1:2)]
head(clean_data)
```

```{r}

#Storing information for each line
name_point <- clean_data[seq(1, length(clean_data), 2)]
state_rating <- clean_data[seq(2, length(clean_data), 2)]
name_point[1]
state_rating[1]
```

```{r}
# Finding data using Regex
name <- str_trim(str_extract(name_point, "(\\s?[A-Z]{2,}\\s?){2,}+"))
state     <- str_trim(str_extract(state_rating, "[A-Z]{2}"))
total_points <- as.numeric(str_extract(name_point, "\\d+\\.\\d+"))
pre_rating <- as.numeric(str_extract(state_rating, "(?<=R:\\s{0,5})\\d+"))
name[1]
state[1]
total_points[1]
pre_rating[1]
```

```{r}
# Information needed to calculate average 
player_id <- as.numeric(str_extract(name_point, "\\d+"))
opponents <- str_extract_all(name_point, "(?<=[WLD]\\s{1,5})\\d+")
opponents_id <- data.frame(id = player_id, rating = pre_rating)
player_id[1]
opponents[1]
opponents_id[1, ]
```

```{r}
#Calculating average opponet rating
avg_opp_rating <- sapply(opponents, function(opp_list) {
  # Convert extracted IDs to numeric
  ids <- as.numeric(opp_list)
  # Find their ratings in our lookup table
  opp_ratings <- opponents_id$rating[match(ids, opponents_id$id)]
  # Return the mean (rounded to nearest integer)
  round(mean(opp_ratings, na.rm = TRUE))
})
avg_opp_rating[1]
```
```{r}
#Create the csv file
final_df <- data.frame(
  `Player’s Name` = name,
  `Player’s State` = state,
  `Total Number of Points` = total_points,
  `Player’s Pre-Rating` = pre_rating,
  `Average Pre Chess Rating of Opponents` = avg_opp_rating
)

head(final_df)
```
```{r}
write.csv(final_df, "Project_1_Chess_Tournament.csv", row.names = FALSE)
```