---
title: "Assignment 5b"
format: html
editor: visual
---
```{r}
library(stringr)
library(tidyr)
library(dplyr)
```


Defining ELO formula
```{r}
calc_expected <- function(p_rating, o_rating) {
  if (is.na(o_rating)) return(0)
  1 / (1 + 10^((o_rating - p_rating) / 400))
}
```

Getting the data
```{r}
# Loading and cleaning the data
data <- readLines("https://raw.githubusercontent.com/Jeovany97/Data-607/refs/heads/main/Project%201/tournamentinfo.txt", warn = FALSE)

clean_data <- data[!str_detect(data, "^-+$")]
clean_data <- clean_data[-(1:2)]
head(clean_data)

#splitting each line into seperate list for easier use
name_point <- clean_data[seq(1, length(clean_data), 2)]
state_rating <- clean_data[seq(2, length(clean_data), 2)]

```

Getting the data on next from the txt
```{r}
name <- str_trim(str_extract(name_point, "(\\s?[A-Z]{2,}\\s?){2,}+"))
player_id <- as.numeric(str_extract(name_point, "\\d+"))
previous_rating <- as.numeric(str_extract(state_rating, "(?<=R:\\s{0,5})\\d+"))
opponents_id <- data.frame(id = player_id, rating = previous_rating)
opponents_faced <- tibble(raw = name_point) %>%
  mutate(
    player_id = as.numeric(str_extract(raw, "^\\s*\\d+")),
    opponent_id = str_extract_all(raw, "(?<=[WLD]\\s{1,5})\\d+")
  ) %>%
  select(player_id, opponent_id)

actual_scores <- as.numeric(str_extract(name_point, "\\d+\\.\\d"))
```

```{r}
rating_lookup <- opponents_id %>% rename(opp_rating = rating)

performance_df <- opponents_faced %>%
  unnest(opponent_id) %>%
  mutate(opponent_id = as.numeric(opponent_id)) %>%
  # Join to get the rating of each opponent
  left_join(rating_lookup, by = c("opponent_id" = "id")) %>%
  # Calculate elo using the elo function made earlier
  rowwise() %>%
  mutate(expected = calc_expected(previous_rating[player_id == player_id][1], opp_rating)) %>%
  group_by(player_id) %>%
  summarise(
    Player_Name = name[unique(player_id)],
    Actual_Score = actual_scores[unique(player_id)],
    Expected_Score = round(sum(expected, na.rm = TRUE), 2),
    Difference = round(Actual_Score - Expected_Score, 2)
  )

overperformers <- performance_df %>%
  arrange(desc(Difference)) %>% 
  head(5)
underperformers <- performance_df %>%
  arrange(Difference) %>% 
  head(5)


```

```{r}
overperformers
```

```{r}
underperformers
```

